language: python
python:
  - "2.7"
os:
  - linux
  - osx
env:
  # 30 corresponds to logging.WARNING
  - TRAVIS_LOG_LEVEL=30
# command to install dependencies
install:
  - python setup.py install
script:
  - nosetests
branches:
  only:
    - master
