# set "sudo: false" to enable travis container-based testing
#sudo: false
group: travis_latest
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
os:
  - linux
env:
  - NOSE_LOG_LEVEL=warning
install:
  - python setup.py install
script:
  - nosetests
branches:
  only:
    - master
